=== joorgee16/Hito-2-lenguaje-de-marcas/pedidos.dtd
<!ELEMENT pedidos (anno+)>
<!ELEMENT anno (trimestre+)>
<!ATTLIST anno
          year CDATA #REQUIRED>
<!ELEMENT trimestre (pedido+)>
<!ATTLIST trimestre
          quarter CDATA #REQUIRED>
<!ELEMENT pedido (cliente, detalle_pedido)>
<!ELEMENT cliente (nombre, apellidos, telefono, direccion, correo, fecha_inclusion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle, ciudad, codigo_postal, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT fecha_inclusion (#PCDATA)>
<!ELEMENT detalle_pedido (numero_pedido, fecha_compra, fecha_entrega, total_factura, productos)>
<!ELEMENT numero_pedido (#PCDATA)>
<!ELEMENT fecha_compra (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total_factura (#PCDATA)>
<!ELEMENT productos (producto)>
<!ELEMENT producto (nombre, referencia, precio, unidades)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

=== joorgee16/Hito-2-lenguaje-de-marcas/pedidos.xml
<!DOCTYPE pedidos SYSTEM "file:/C:/Users/jorge/OneDrive/Escritorio/Hito%202%20Lenguaje%20de%20marcas/pedidos.dtd">
<?xml-stylesheet type="text/xsl" href="file:/C:/Users/jorge/OneDrive/Escritorio/Hito%202%20Lenguaje%20de%20marcas/pedidos%202.xsl"?>
<pedidos>
    <anno year="2021">
        <trimestre quarter="1">
            <pedido>
                <cliente>
                    <nombre>Juan</nombre>
                    <apellidos>Pérez</apellidos>
                    <telefono>123456789</telefono>
                    <direccion>
                        <calle>Calle 123</calle>
                        <ciudad>Ciudad A</ciudad>
                        <codigo_postal>12345</codigo_postal>
                        <provincia>Provincia X</provincia>
                    </direccion>
                    <correo>juan@example.com</correo>
                    <fecha_inclusion>2021-01-05</fecha_inclusion>
                </cliente>
                <detalle_pedido>
                    <numero_pedido>001</numero_pedido>
                    <fecha_compra>2021-01-05</fecha_compra>
                    <fecha_entrega>2021-01-10</fecha_entrega>
                    <total_factura>150.00</total_factura>
                    <productos>
                        <producto>
                            <nombre>Camiseta</nombre>
                            <referencia>CAM001</referencia>
                            <precio>30.00</precio>
                            <unidades>2</unidades>
                        </producto>
                        <!-- Otros productos -->
                    </productos>
                </detalle_pedido>
            </pedido>
            <pedido>
                <cliente>
                    <nombre>Juan</nombre>
                    <apellidos>Pérez</apellidos>
                    <telefono>123456789</telefono>
                    <direccion>
                        <calle>Calle 123</calle>
                        <ciudad>Ciudad A</ciudad>
                        <codigo_postal>12345</codigo_postal>
                        <provincia>Provincia X</provincia>
                    </direccion>
                    <correo>juan@example.com</correo>
                    <fecha_inclusion>2021-01-05</fecha_inclusion>
                </cliente>
                <detalle_pedido>
                    <numero_pedido>002</numero_pedido>
                    <fecha_compra>2021-01-05</fecha_compra>
                    <fecha_entrega>2021-01-10</fecha_entrega>
                    <total_factura>150.00</total_factura>
                    <productos>
                        <producto>
                            <nombre>Camiseta</nombre>
                            <referencia>CAM001</referencia>
                            <precio>30.00</precio>
                            <unidades>2</unidades>
                        </producto>
                        <!-- Otros productos -->
                    </productos>
                </detalle_pedido>
            </pedido>
                        <pedido>
                <cliente>
                    <nombre>Juan</nombre>
                    <apellidos>Pérez</apellidos>
                    <telefono>123456789</telefono>
                    <direccion>
                        <calle>Calle 123</calle>
                        <ciudad>Ciudad A</ciudad>
                        <codigo_postal>12345</codigo_postal>
                        <provincia>Provincia X</provincia>
                    </direccion>
                    <correo>juan@example.com</correo>
                    <fecha_inclusion>2021-01-05</fecha_inclusion>
                </cliente>
                <detalle_pedido>
                    <numero_pedido>003</numero_pedido>
                    <fecha_compra>2021-01-05</fecha_compra>
                    <fecha_entrega>2021-01-10</fecha_entrega>
                    <total_factura>150.00</total_factura>
                    <productos>
                        <producto>
                            <nombre>Camiseta</nombre>
                            <referencia>CAM001</referencia>
                            <precio>30.00</precio>
                            <unidades>2</unidades>
                        </producto>
                        <!-- Otros productos -->
                    </productos>
                </detalle_pedido>
            </pedido>
                        <pedido>
                <cliente>
                    <nombre>Juan</nombre>
                    <apellidos>Pérez</apellidos>
                    <telefono>123456789</telefono>
                    <direccion>
                        <calle>Calle 123</calle>
                        <ciudad>Ciudad A</ciudad>
                        <codigo_postal>12345</codigo_postal>
                        <provincia>Provincia X</provincia>
                    </direccion>
                    <correo>juan@example.com</correo>
                    <fecha_inclusion>2021-01-05</fecha_inclusion>
                </cliente>
                <detalle_pedido>
                    <numero_pedido>004</numero_pedido>
                    <fecha_compra>2021-01-05</fecha_compra>
                    <fecha_entrega>2021-01-10</fecha_entrega>
                    <total_factura>80.00</total_factura>
                    <productos>
                        <producto>
                            <nombre>Chaqueta</nombre>
                            <referencia>CHA001</referencia>
                            <precio>800.00</precio>
                            <unidades>2</unidades>
                        </producto>
                        <!-- Otros productos -->
                    </productos>
                </detalle_pedido>
            </pedido>
                        <pedido>
                <cliente>
                    <nombre>Juan</nombre>
                    <apellidos>Pérez</apellidos>
                    <telefono>123456789</telefono>
                    <direccion>
                        <calle>Calle 123</calle>
                        <ciudad>Ciudad A</ciudad>
                        <codigo_postal>12345</codigo_postal>
                        <provincia>Provincia X</provincia>
                    </direccion>
                    <correo>juan@example.com</correo>
                    <fecha_inclusion>2021-01-05</fecha_inclusion>
                </cliente>
                <detalle_pedido>
                    <numero_pedido>005</numero_pedido>
                    <fecha_compra>2021-01-05</fecha_compra>
                    <fecha_entrega>2021-01-10</fecha_entrega>
                    <total_factura>40.00</total_factura>
                    <productos>
                        <producto>
                            <nombre>Pantalon</nombre>
                            <referencia>PAN001</referencia>
                            <precio>40.00</precio>
                            <unidades>2</unidades>
                        </producto>
                        <!-- Otros productos -->
                    </productos>
                </detalle_pedido>
            </pedido>
                        <pedido>
                <cliente>
                    <nombre>Carlos</nombre>
                    <apellidos>Lopez</apellidos>
                    <telefono>987654321</telefono>
                    <direccion>
                        <calle>Calle 4</calle>
                        <ciudad>Ciudad B</ciudad>
                        <codigo_postal>54321</codigo_postal>
                        <provincia>Provincia Z</provincia>
                    </direccion>
                    <correo>Carlos@example.com</correo>
                    <fecha_inclusion>2021-01-07</fecha_inclusion>
                </cliente>
                <detalle_pedido>
                    <numero_pedido>006</numero_pedido>
                    <fecha_compra>2021-01-07</fecha_compra>
                    <fecha_entrega>2021-01-12</fecha_entrega>
                    <total_factura>16.00</total_factura>
                    <productos>
                        <producto>
                            <nombre>Camiseta</nombre>
                            <referencia>CAM001</referencia>
                            <precio>16.00</precio>
                            <unidades>1</unidades>
                        </producto>
                        <!-- Otros productos -->
                    </productos>
                </detalle_pedido>
            </pedido>
                        <pedido>
                <cliente>
                    <nombre>Ana</nombre>
                    <apellidos>Martinez</apellidos>
                    <telefono>652412542</telefono>
                    <direccion>
                        <calle>Calle 5</calle>
                        <ciudad>Ciudad B</ciudad>
                        <codigo_postal>28903</codigo_postal>
                        <provincia>Provincia Y</provincia>
                    </direccion>
                    <correo>Ana@example.com</correo>
                    <fecha_inclusion>2021-01-07</fecha_inclusion>
                </cliente>
                <detalle_pedido>
                    <numero_pedido>007</numero_pedido>
                    <fecha_compra>2021-01-07</fecha_compra>
                    <fecha_entrega>2021-01-14</fecha_entrega>
                    <total_factura>40.00</total_factura>
                    <productos>
                        <producto>
                            <nombre>Pantalon</nombre>
                            <referencia>PAN001</referencia>
                            <precio>40.00</precio>
                            <unidades>3</unidades>
                        </producto>
                        <!-- Otros productos -->
                    </productos>
                </detalle_pedido>
